export const songs = [
  {
    artist: "Great Artist",
    name: "The Greatest Song",
    image: "https://beatsaber.com/images/music/ID.jpg",
    stars: 0,
    score: "256,99",
    maxcombo: "245",
    fullcombo: "0",
    badcuts: "1",
    pp: "69,13",
    predictedpp: "70",
    accuracy: "88.34%",
    predictedaccuracy: "90%",
  },
  {
    artist: "Another Great Artist",
    name: "The Greatest Song Of All Time",
    image: "https://beatsaber.com/images/music/music4.jpg",
    stars: 0,
    score: "206,99",
    maxcombo: "245",
    fullcombo: "0",
    badcuts: "1",
    pp: "39,13",
    predictedpp: "70",
    accuracy: "18.34%",
    predictedaccuracy: "90%",
  },
  {
    artist: "Extra Popular One",
    name: "Most Popular Single Ever",
    image: "https://beatsaber.com/images/music/music5.jpg",
    stars: 0,
    score: "256,99",
    maxcombo: "245",
    fullcombo: "0",
    badcuts: "1",
    pp: "69,13",
    predictedpp: "70",
    accuracy: "88.34%",
    predictedaccuracy: "90%",
  },
  {
    artist: "Another One",
    name: "Just Another Song",
    image: "https://beatsaber.com/images/music/music6.jpg",
    stars: 0,
    score: "256,99",
    maxcombo: "245",
    fullcombo: "0",
    badcuts: "1",
    pp: "69,13",
    predictedpp: "70",
    accuracy: "88.34%",
    predictedaccuracy: "90%",
  },
  {
    artist: "A Weird One",
    name: "What Am I Even Looking At",
    image: "https://beatsaber.com/images/music/music9.jpg",
    stars: 0,
    score: "256,99",
    maxcombo: "245",
    fullcombo: "0",
    badcuts: "1",
    pp: "69,13",
    predictedpp: "70",
    accuracy: "88.34%",
    predictedaccuracy: "90%",
  },
  {
    artist: "A Cringe Artist",
    name: "Dies From Cringe",
    image: "https://beatsaber.com/images/music/music12.jpg",
    stars: 0,
    score: "256,99",
    maxcombo: "245",
    fullcombo: "0",
    badcuts: "1",
    pp: "69,13",
    predictedpp: "70",
    accuracy: "88.34%",
    predictedaccuracy: "90%",
  },
  {
    artist: "Extra Cringe Artist",
    name: "The Whole World Is Cringe Honestly",
    image: "https://beatsaber.com/images/music/music14.jpg",
    stars: 0,
    score: "256,99",
    maxcombo: "245",
    fullcombo: "0",
    badcuts: "1",
    pp: "69,13",
    predictedpp: "70",
    accuracy: "88.34%",
    predictedaccuracy: "90%",
  },
  {
    artist: "Some Absurd Name",
    name: "Eman Drusba Emos",
    image: "https://beatsaber.com/images/music/music15.jpg",
    stars: 0,
    score: "256,99",
    maxcombo: "245",
    fullcombo: "0",
    badcuts: "1",
    pp: "69,13",
    predictedpp: "70",
    accuracy: "88.34%",
    predictedaccuracy: "90%",
  },
  {
    artist: "Super Cool Rock Band",
    name: "Like So Cool",
    image: "https://beatsaber.com/images/music/music17.jpg",
    stars: 0,
    score: "256,99",
    maxcombo: "245",
    fullcombo: "0",
    badcuts: "1",
    pp: "69,13",
    predictedpp: "70",
    accuracy: "88.34%",
    predictedaccuracy: "90%",
  },
  {
    artist: "Uber Cringe Band",
    name: "Lol Kek",
    image: "https://beatsaber.com/images/music/music18.jpg",
    stars: 0,
    score: "256,99",
    maxcombo: "245",
    fullcombo: "0",
    badcuts: "1",
    pp: "69,13",
    predictedpp: "70",
    accuracy: "88.34%",
    predictedaccuracy: "90%",
  },
];
